#!/bin/bash

NAME="My flask apps"
FLASKDIR=/root/flask_gunicorn
VENVDIR=/root/py_flask_gunicorn_env
SOCKFILE=/tmp/gunicorn.sock
USER=root
GROUP=root
NUM_WORKERS=3

echo "Starting $NAME"

# activate the virtualenv
cd $FLASKDIR
source $VENVDIR/bin/activate

export PYTHONPATH=$FLASKDIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your unicorn
exec gunicorn main:app -b 127.0.0.1:8000 \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --log-level=debug \
  --bind=unix:$SOCKFILE
